# Apply the intersection mask of body mask and valid region mask.

# Only use the sessions with BMI value pass temporal consistency check.

# 0_3 -> 0_2, modification on K-Fold split: 1) session level split; 2) shuffle before split.
# Target is to reduce the inter-fold variation.

# A new project after fix the rounding fov problem.

task: 'BMI'
exp_dir: '/nfs/masi/xuk9/SPORE/CAC_class/output/simg_bmi_regression_3.6.4'
input_img_dir: '/nfs/masi/xuk9/SPORE/CAC_class/data/atlas/valid_region/s6.1_int'
input_jac_dir: '/nfs/masi/xuk9/SPORE/CAC_class/data/atlas/valid_region/s6.2_jac'
input_valid_mask_dir: '/nfs/masi/xuk9/SPORE/CAC_class/data/atlas/valid_region/s6_body_mask_intersect'
input_d_index_dir: '/nfs/masi/xuk9/SPORE/CAC_class/data/atlas/d_index/s1_resampled'
learning_rate: 0.00001   #default 0.0001s
res:
  - 192
  - 128
  - 64
imsize:
  - 192
  - 128
  - 64
sample_size: 128
sample_duration: 64
batch_size: 2
fcnum: 1536
networkName: 'resnet34'
label_csv: '/nfs/masi/xuk9/SPORE/CAC_class/clinical/label_full_combined.csv'
train_file_list_txt: '/nfs/masi/xuk9/SPORE/CAC_class/file_lists/result_temporal'
add_intensity_map: False
add_jacobian_map: True
add_valid_mask_map: False
add_d_index_map: False
apply_valid_mask: False
add_jac_elem_maps: False
data_augmentation: True
img_max: 600
img_min: -1000
jac_max: 1.5
jac_min: -1.5
start_epoch: 0
epoch_num: 201
lr_scheduler_step: 10
lr_scheduler_gamma: 0.8
fold_num: 5
output_epoch_model: False
no_increase_step_limit: 50
gcam_target_layer: layer2