# Apply the intersection mask of body mask and valid region mask.


task: 'BMI'
exp_dir: '/proj_root/output/simg_bmi_regression_3.5'
input_img_dir: '/proj_root/data/atlas/valid_region/s6.1.1_body_mask_int'
input_jac_dir: '/proj_root/data/atlas/valid_region/s6.2.1_body_mask_jac'
input_valid_mask_dir: '/proj_root/data/atlas/valid_region/s6_body_mask_intersect'
input_d_index_dir: '/proj_root/data/atlas/d_index/s1_resampled'
learning_rate: 0.00001   #default 0.0001s
res:
  - 192
  - 128
  - 64
imsize:
  - 192
  - 128
  - 64
sample_size: 128
sample_duration: 64
batch_size: 2
fcnum: 1536
networkName: 'resnet34'
label_csv: '/proj_root/clinical/label_full_combined.csv'
train_file_list_txt: '/proj_root/file_lists/complete_list'
add_intensity_map: False
add_jacobian_map: True
add_valid_mask_map: False
add_d_index_map: False
apply_valid_mask: False
data_augmentation: True
img_max: 600
img_min: -1000
jac_max: 1.5
jac_min: -1.5
start_epoch: 0
epoch_num: 201
lr_scheduler_step: 10
lr_scheduler_gamma: 0.8
fold_num: 5
output_epoch_model: False
no_increase_step_limit: 50
gcam_target_layer: layer2